medicines={
    Augmentin:"amoxicillin clavulanate",
    Azomax:"azithromycin",
    Brufen:"ibuprofen",
    Calpol:"acetaminophen",
    Dicloran:"diclofenac",
    Disprin:"aspirin",
    Flagyl:"metronidazole",
    Glucophage:"metformin",
    Imodium:"loperamide",
    Motilium:"domperidone",
    Nexum:"esomeprazole",
    Norvasc:'amlodipine',
    Nuberol:"paracetamol + orphenadrine",
    Panadol:"acetaminophen",
    Ponstan:"mefenamic acid",
    Rigix:"cetirizine",
    Risek:"omeprazole",
    Synflex:"naproxen",
    Tenormin:"atenolol",
    Ventolin:"albuterol(salbutamol)"

}